### ISSUE TITLE
Compliments

### ISSUE THREAD

**Issue by hdrdavies** [CoffeeDotFilter/blog#27]
- Nice readme!
- Love the fonts & general look of the app
- Good work on your coverage
- Where did you get those coffee icons from? 

Now that's over, I can scrutinize your code :wink:

**Comment by sohilpandya** [comment]
I have to say though the testing in server.js needs a little bit of work, there are three reply.views that are in red.

**Comment by hdrdavies** [comment]
Also well done for using es6!

**Comment by hdrdavies** [comment]
Also, how did you find out about [moment.js](https://github.com/CoffeeDotFilter/blog/blob/a8e8a0af2e7a1d7eb10adea0f46bc80e6dfd5fc9/views/helpers/dateHelper.js#L3)! I only found out today!!!!1111!!111!1111oneoneone

**Comment by hdrdavies** [comment]
and nice use of helper files

**Comment by andrewMacmurray** [comment]
@hdrdavies thanks, glad you like, I made the coffee icons in illustrator. moment.js was a bit of a random find, it's really nice! helpers ftw!

@sohilpandya will have a look at the server tests

**Comment by hdrdavies** [comment]
@andrewMacmurray Love those coffee icons. Next time I want some funky icons you might get a call :wink:

**Comment by andrewMacmurray** [comment]
@sohilpandya have got server tests working for 2 out of the 3 with #37 , the third one for the admin view we were having problems with getting travis to recognise environment variable for usernames and passwords

**Comment by andrewMacmurray** [comment]
@hdrdavies of course, happy to help :wink:
