### ISSUE TITLE
Why only one commit by jack? 

### ISSUE THREAD

**Issue by sohilpandya** [CoffeeDotFilter/blog#29]
@oturnermajor @JackTierney @andrewMacmurray 

Interesting read for the graphs, only one commit in the last 4 days by @JackTierney. Is it because he doesn't have a mac?

**Comment by JackTierney** [comment]
Basically yes, we work from the big screen and my computer doesn't have a driver to hook up to the larger screen so we ending up commiting from one of the macs...yes, yes, Ubuntu is shit.

**Comment by hdrdavies** [comment]
No it's not Jack. Don't listen to the haters.

**Comment by hdrdavies** [comment]
And there's nothing wrong with Pair Programming!

**Comment by sohilpandya** [comment]
Lol.

**Comment by JackTierney** [comment]
@sohilpandya issue response time, would you do the honours of closing this Sohil?
