### ISSUE TITLE
Code readibility

### ISSUE THREAD

**Issue by hdrdavies** [CoffeeDotFilter/blog#30]
Just a small note on trying to make your code readable. It's really important for people who might be inheriting your project, as well as you guys coming back to it! 

The indentation is a little bit messy in some places e.g.

https://github.com/CoffeeDotFilter/blog/blob/a8e8a0af2e7a1d7eb10adea0f46bc80e6dfd5fc9/server.js#L39

and you seem to be switching between tabs and spaces:

https://github.com/CoffeeDotFilter/blog/blob/a8e8a0af2e7a1d7eb10adea0f46bc80e6dfd5fc9/server.js#L74

https://github.com/CoffeeDotFilter/blog/blob/a8e8a0af2e7a1d7eb10adea0f46bc80e6dfd5fc9/server.js#L39

It's good to agree as a team before a project how you're going to indent code, name files etc.

see [here](http://www.codereadability.com/why-use-a-style-guide/) for why you might want to use it, and [here](https://github.com/airbnb/javascript) for AirBnB's style guide! You'll be able to find similar style guides for jQuery and MDN etc. etc.

Really impressed with that server.js file - you've grasped a lot of hapi concepts ! Good job!

**Comment by andrewMacmurray** [comment]
@hdrdavies thanks, this should be better with pr #33

**Comment by hdrdavies** [comment]
Lovely stuff @andrewMacmurray I like the way you've lined up the colons on CSS - not something I've seen before :wink: 

Do resist the urge to use atom beautify / sublime prettify - it can make you lazy in how you layout your code and anything that automates stuff for you like that does impair learning. Not that I'm claiming you've been using it of course!
