### ISSUE TITLE
What's this file doing (out of interest)?

### ISSUE THREAD

**Issue by hdrdavies** [CoffeeDotFilter/blog#31]
https://github.com/CoffeeDotFilter/blog/blob/a8e8a0af2e7a1d7eb10adea0f46bc80e6dfd5fc9/public/dashboard.js

**Comment by andrewMacmurray** [comment]
@hdrdavies this is to add the TinyMCE editor for the dashboard

**Comment by hdrdavies** [comment]
Looks cool!

**Comment by hdrdavies** [comment]
But waaaaait a minute- what happens to not using libraries? :grimacing:

**Comment by andrewMacmurray** [comment]
@hdrdavies haha but it was in the project stretch goals!

**Comment by hdrdavies** [comment]
@andrewMacmurray Forgive meeeeeee :pray:
